In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a -1

array([-1,  0,  1,  2,  3])

In [4]:
a * 5

array([ 0,  5, 10, 15, 20])

In [8]:
b = np.ones(5)+1
b

array([2., 2., 2., 2., 2.])

In [9]:
a - b

array([-2., -1.,  0.,  1.,  2.])

In [10]:
a * b

array([0., 2., 4., 6., 8.])

In [11]:
c = np.diag([1,2,3,4,5])
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [12]:
c*c

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [13]:
c.dot(c)

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])