In [1]:
import numpy as np
a = np.array([1,2,4,8,9])
print(a)

[1 2 4 8 9]


In [2]:
b = np.arange(100,200,2)
print(b)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


In [6]:
c = np.array([[[1,9],[10,3]],[[4,4],[8,7]]])
print(c.ndim)
print(c.shape)

3
(2, 2, 2)


In [11]:
#linear space
print(np.linspace(0,1,5))
print(np.linspace(0,8,5))

[0.   0.25 0.5  0.75 1.  ]
[0. 2. 4. 6. 8.]


In [14]:
#common arrays
print(np.ones((3,3)))
print(np.zeros((4,4)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
#identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#create array using diag function
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
#create arrays using random
np.random.rand(4)

array([0.55396745, 0.16489592, 0.26105716, 0.95614734])

In [20]:
np.random.randn(4)

array([ 0.60876577, -0.38774418, -0.44977682, -0.16291097])

In [21]:
"""
Data Types
"""
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [22]:
a = np.array([1,2,3],'float64')
print(a)
print(a.dtype)

[1. 2. 3.]
float64


In [23]:
a = np.array([True, False,True])
a.dtype

dtype('bool')

In [25]:
a = np.array([True, 1, 2])
print(a.dtype)
print(a)

int64
[1 1 2]


In [26]:
a = np.array(["a", 1 ,10, True])
print(a)
print(a.dtype)

['a' '1' '10' 'True']
<U4


In [27]:
a = np.array(['hello','world'])
a.dtype

dtype('<U5')

In [28]:
a = np.array([1+2j, 3+4j])
a.dtype

dtype('complex128')

In [29]:
#Indexing
a = np.arange(10)
a[5]

5

In [30]:
a = np.diag([1,2,3])
a[(2,2)]

3

In [32]:
#assigning a value
a[(2,1)] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]
