In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a -1

array([-1,  0,  1,  2,  3])

In [4]:
a * 5

array([ 0,  5, 10, 15, 20])

In [8]:
b = np.ones(5)+1
b

array([2., 2., 2., 2., 2.])

In [9]:
a - b

array([-2., -1.,  0.,  1.,  2.])

In [10]:
a * b

array([0., 2., 4., 6., 8.])

In [11]:
c = np.diag([1,2,3,4,5])
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [12]:
c*c

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [13]:
c.dot(c)

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [3]:
#comparisions
a = np.array([1,2,3,4])
print(a)
b = np.array([3,4,3,3])
print(b)

[1 2 3 4]
[3 4 3 3]


In [4]:
a == b

array([False, False,  True, False])

In [5]:
 a > b

array([False, False, False,  True])

In [6]:
 c = np.array([1,2,3,4])
 np.array_equal(a,b)

False

In [7]:
np.array_equal(a,c)

True

In [8]:
#Logical operator
a = np.array([1,1,0,1], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [9]:
np.logical_and(a,b)

array([ True, False, False, False])

In [2]:
#transcendental functions
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [4]:
np.log(a)

/home/aashish/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [5]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])